# Generated by Django 4.2.7 on 2024-01-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farforre', '0002_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Колір'),
        ),
    ]
