# Generated by Django 4.2.7 on 2024-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farforre', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prise',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ціна'),
        ),
    ]
