# Generated by Django 4.2.7 on 2024-01-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farforre', '0004_product_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='farforre.product', verbose_name='Супутні товари'),
        ),
    ]
